# Generated by Django 5.2.7 on 2025-11-10 13:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['author', 'title']},
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated',
        ),
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
